name: SSVP Web - Ollama local
version: 0.0.1
schema: v1

models:
  - name: Qwen Coder Local
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://localhost:11434
    roles:
      - chat
      - edit
      - apply

  - name: Llama Local
    provider: ollama
    model: llama3.1:8b
    apiBase: http://localhost:11434
    roles:
      - chat

embeddings:
  - name: Nomic Local
    provider: ollama
    model: nomic-embed-text:latest
    apiBase: http://localhost:11434
